#Args=--no-fallback -H:IncludeLocales=ar,en -H:-CheckToolchain \
#     --initialize-at-run-time=javafx.scene.Node \
#     --initialize-at-run-time=javafx.scene.chart.Axis$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.chart.NumberAxis$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.chart.ValueAxis$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.Control$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.DialogPane$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.Labeled$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.ListView$EditEvent \
#     --initialize-at-run-time=javafx.scene.control.ListView$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.PopupControl \
#     --initialize-at-run-time=javafx.scene.control.ScrollBar$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.ScrollPane$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.Separator$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.SkinBase$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.Slider$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.SplitPane$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.TabPane$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.TextArea$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.TextField$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.TextInputControl$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.TitledPane$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.skin.CellSkinBase$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.skin.ProgressBarSkin$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.skin.ProgressIndicatorSkin \
#     --initialize-at-run-time=javafx.scene.control.skin.TabPaneSkin$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.control.skin.TextInputControlSkin \
#     --initialize-at-run-time=javafx.scene.control.skin.TextInputControlSkin$StyleableProperties \
#     --initialize-at-run-time=javafx.stage.Screen \
#     --initialize-at-run-time=javafx.scene.CssStyleHelper \
#     --initialize-at-run-time=javafx.scene.image.ImageView$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.layout.GridPane$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.layout.HBox$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.layout.Region$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.layout.StackPane$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.layout.VBox$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.shape.Rectangle$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.shape.Shape$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.text.Text$StyleableProperties \
#     --initialize-at-run-time=javafx.scene.web.WebEngine \
#     --initialize-at-run-time=javafx.scene.web.WebView$StyleableProperties \
#     --initialize-at-run-time=com.sun.glass.ui.Clipboard \
#     --initialize-at-run-time=com.sun.glass.ui.win.WinAccessible \
#     --initialize-at-run-time=com.sun.glass.ui.win.WinApplication \
#     --initialize-at-run-time=com.sun.glass.ui.win.WinCursor \
#     --initialize-at-run-time=com.sun.glass.ui.win.WinGestureSupport \
#     --initialize-at-run-time=com.sun.glass.ui.win.WinPixels \
#     --initialize-at-run-time=com.sun.glass.ui.win.WinTimer \
#     --initialize-at-run-time=com.sun.glass.ui.win.WinWindow \
#     --initialize-at-run-time=com.sun.glass.ui.win.WinView \
#     --initialize-at-run-time=com.sun.javafx.font.AndroidFontFinder \
#     --initialize-at-run-time=com.sun.javafx.font.DFontDecoder \
#     --initialize-at-run-time=com.sun.javafx.font.MacFontFinder \
#     --initialize-at-run-time=com.sun.javafx.font.PrismFontFactory \
#     --initialize-at-run-time=com.sun.javafx.font.PrismFontFile \
#     --initialize-at-run-time=com.sun.javafx.font.directwrite.DWFontStrike \
#     --initialize-at-run-time=com.sun.javafx.font.directwrite.OS \
#     --initialize-at-run-time=com.sun.javafx.iio.jpeg.JPEGImageLoader \
#     --initialize-at-run-time=com.sun.javafx.scene.control.ContextMenuContent$StyleableProperties \
#     --initialize-at-run-time=com.sun.javafx.scene.control.LabeledHelper \
#     --initialize-at-run-time=com.sun.javafx.scene.control.LabeledImpl$StyleableProperties \
#     --initialize-at-run-time=com.sun.javafx.scene.control.Properties \
#     --initialize-at-run-time=com.sun.javafx.scene.control.behavior.TextInputControlBehavior \
#     --initialize-at-run-time=com.sun.javafx.scene.control.skin.FXVKSkin \
#     --initialize-at-run-time=com.sun.javafx.scene.control.skin.Utils \
#     --initialize-at-run-time=com.sun.javafx.scene.NodeHelper \
#     --initialize-at-run-time=com.sun.javafx.text.GlyphLayoutManager \
#     --initialize-at-run-time=com.sun.javafx.text.PrismTextLayoutFactory \
#     --initialize-at-run-time=com.sun.javafx.tk.quantum.PrismImageLoader2$AsyncImageLoader \
#     --initialize-at-run-time=com.sun.javafx.webkit.prism.PrismGraphicsManager \
#     --initialize-at-run-time=com.sun.marlin.DMarlinRenderingEngine \
#     --initialize-at-run-time=com.sun.marlin.MarlinUtils \
#     --initialize-at-run-time=com.sun.marlin.MaskMarlinAlphaConsumer \
#     --initialize-at-run-time=com.sun.prism.PresentableState \
#     --initialize-at-run-time=com.sun.prism.d3d.D3DPipeline \
#     --initialize-at-run-time=com.sun.prism.es2.ES2Pipeline \
#     --initialize-at-run-time=com.sun.prism.impl.BaseResourcePool \
#     --initialize-at-run-time=com.sun.prism.impl.PrismSettings \
#     --initialize-at-run-time=com.sun.prism.impl.ps.PaintHelper \
#     --initialize-at-run-time=com.sun.prism.sw.SWPipeline \
#     --initialize-at-run-time=com.sun.scenario.animation.AbstractPrimaryTimer \
#     --initialize-at-run-time=com.sun.webkit.WebPage \
#     --initialize-at-run-time=org.kordamp.ikonli.javafx.FontIcon$StyleableProperties \
#     --initialize-at-run-time=org.kordamp.ikonli.javafx.StackedFontIcon$StyleableProperties
#Args=--trace-object-instantiation=com.sun.prism.d3d.D3DPipeline --trace-object-instantiation=java.net.Inet6Address
Args=--no-fallback -H:IncludeLocales=ar,en --initialize-at-run-time=org.kordamp.ikonli.javafx.FontIcon$StyleableProperties --initialize-at-run-time=org.kordamp.ikonli.javafx.StackedFontIcon$StyleableProperties --trace-object-instantiation=javafx.scene.paint.Color

# -H:NativeLinkerOption=/SUBSYSTEM:WINDOWS -H:NativeLinkerOption=/ENTRY:mainCRTStartup
# com.sun.glass.ui.win.WinApplication: no glass in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
# com.sun.prism.d3d.D3DPipeline: no prism_d3d in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
# com.sun.javafx.font.directwrite.OS: no javafx_font in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
# com.sun.javafx.font.AndroidFontFinder: no javafx_font in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
# com.sun.javafx.font.DFontDecoder: no javafx_font in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
# com.sun.javafx.text.PrismTextLayoutFactory: no javafx_font in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
# com.sun.javafx.font.directwrite.DWFontStrike: no javafx_font in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
# com.sun.javafx.text.GlyphLayoutManager: no javafx_font in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
# com.sun.javafx.iio.jpeg.JPEGImageLoader: no javafx_iio in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
