# Reference: https://quarkus.io/guides/all-config

quarkus.analytics.disabled=true
quarkus.log.category."javafx".level=ERROR
quarkus.log.category."io.quarkiverse.fx".level=WARNING

quarkus.log.file.enable=true
quarkus.log.file.path=${user.home}/quran-desktop/logs/app.log