# Reference: https://quarkus.io/guides/all-config

quarkus.rest-client."com.quran.labs.desktop.login.clients.LoginRestClient".url=https://quran-api.fridaynightdev.com
quarkus.rest-client."com.quran.labs.desktop.login.clients.StorageRestClient".url=https://dev-storage.fridaynightdev.com:8443

# If set to true, the server trusts all certificates. This is useful for testing, but should not be used in production.
quarkus.tls.trust-all=true