# labels

window.title = Quran Desktop App
label.appLanguage = App Language:
message.anotherInstanceRunning = Another instance of the application is already running!
message.confirmExitingApp = Are you sure you want ot exit the application?

label.momentsAgo=Moments ago
label.oneMinuteAgo=1 minute ago
label.twoMinutesAgo=2 minutes ago
label.threeToTenMinutesAgo={0} minutes ago
label.moreThanTenMinutesAgo={0} minutes ago