# labels

window.title = Quran Desktop App
label.appLanguage = App Language:
message.anotherInstanceRunning = Another instance of the application is already running!
message.confirmExitingApp = Are you sure you want ot exit the application?

label.momentsAgo=Moments ago
label.oneMinuteAgo=1 minute ago
label.twoMinutesAgo=2 minutes ago
label.threeToTenMinutesAgo={0} minutes ago
label.moreThanTenMinutesAgo={0} minutes ago
label.chaptersList=Chapters List
label.bookmarks=Bookmarks
label.reading=Reading
label.translations=Translations
label.part=Part
label.chapter=Chapter
label.page=Page
label.recitation=Recitation
label.fromChapter=From chapter
label.toChapter=To chapter
label.ayah=Ayah
label.toPageEnd=To end of page
label.toJuzEnd=To end of Juz
label.toHizbEnd=To end of Hizb
label.recitationRepetition=Recitation repetition
label.eachAyahRepetition=Each ayah repetition
label.reciter=Reciter